version: "3"
services:
  web:
    container_name: web
    restart: always
    build: ../frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - front
  api:
    container_name: api
    restart: always
    build: ../backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - front
      - back
  database:
    container_name: database
    image: mongo
    restart: always
    volumes:
      - ./.mongo_volume:/data/db
    ports:
      - "27017:27019"
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge