version: "3"
services:
  web:
    container_name: web
    restart: always
    build: ../frontend
    ports:
      - "8080:8080"
    links:
      - api
  api:
    container_name: api
    restart: always
    build: ../backend
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./.mongo_volume:/data/db
    ports:
      - "27017:27019"