version: "3"
services:
  web:
    container_name: web
    restart: always
    build: ../frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - front
  api:
    container_name: api
    restart: always
    build: ../backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - front
      - back
  database:
    container_name: database
    image: mongo
    restart: always
    volumes:
      - ./.mongo_volume:/data/db
    ports:
      - "27017:27019"
    networks:
      - back
  proxy:
    container_name: proxy
    image: nginx
    restart: always
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/conf.d/proxy.conf
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
      - api
    networks:
      - front
      - docker-network

networks:
  front:
    driver: bridge
  back:
    driver: bridge
  docker-network:
    driver: bridge