GET http://localhost:3000/sentences

###

GET http://localhost:3000/sentences/5e25df70e632882a22eef95c

###

DELETE http://localhost:3000/sentences/5e25df70e632882a22eef95c

###

POST http://localhost:3000/sentences
Content-Type: application/json

{
  "text": "Hello"
}

###

PATCH http://localhost:3000/sentences/5e25df70e632882a22eef95c
Content-Type: application/json 

{
  "text": "Bye"
}